# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGelinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
