# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gelinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaborGelinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=100, unique=True, verbose_name='Sabor')),
                ('qtd', models.IntegerField(verbose_name='Quatidade')),
                ('valor_uni', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'SaborGelinho',
                'default_related_name': 'Tipos',
                'verbose_name_plural': 'SaboresGelinhos',
                'ordering': ['sabor'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipogelinho',
            options={'ordering': ['tipo'], 'verbose_name': 'TipoGelinho', 'verbose_name_plural': 'TiposGelinho'},
        ),
        migrations.AlterField(
            model_name='tipogelinho',
            name='tipo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='saborgelinho',
            name='tipo_gelinho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tipos', to='gelinho.TipoGelinho'),
        ),
    ]
